server:
  port: ${PORT:8080}
jsch:
  dotSsh: '.ssh'
  knownHosts.file: '.ssh/known_hosts'
  privateKey.files: '.ssh'
charlie:
  token: '767946678:AAGhduP0bRqNpubiS8h77qUXp7DzGdgB3p0'
  username: 'charlie12bot'
